import type { EmailOtpType } from "@supabase/supabase-js";
import { type NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// Supabase forwards verification failures to the redirect_to URL with the
// error info in the URL hash, which never reaches the server. The root layout
// catches that case client-side. Here we only see query-string failures —
// missing code, code-exchange errors, etc.
//
// Two arrival shapes we handle:
//   * `?code=...`                 — PKCE flow used by signInWithOtp / OAuth
//   * `?token_hash=...&type=...`  — token-hash flow used by admin invites,
//                                   magic links generated by generateLink, and
//                                   recovery / email-change links
const OTP_TYPES = new Set<EmailOtpType>([
	"email",
	"email_change",
	"invite",
	"magiclink",
	"recovery",
	"signup",
]);

function isOtpType(value: string | null): value is EmailOtpType {
	return value !== null && OTP_TYPES.has(value as EmailOtpType);
}

export async function GET(request: NextRequest) {
	const { searchParams, origin } = new URL(request.url);
	const code = searchParams.get("code");
	const tokenHash = searchParams.get("token_hash");
	const type = searchParams.get("type");
	const next = searchParams.get("next") ?? "/dashboard";

	const queryError = searchParams.get("error");
	const queryErrorCode = searchParams.get("error_code");
	const queryErrorDescription = searchParams.get("error_description");
	if (queryError || queryErrorCode) {
		const params = new URLSearchParams();
		if (queryError) params.set("error", queryError);
		if (queryErrorCode) params.set("error_code", queryErrorCode);
		if (queryErrorDescription)
			params.set("error_description", queryErrorDescription);
		return NextResponse.redirect(`${origin}/auth/error?${params.toString()}`);
	}

	const supabase = await createClient();

	if (tokenHash && isOtpType(type)) {
		const { error } = await supabase.auth.verifyOtp({
			type,
			token_hash: tokenHash,
		});
		if (!error) {
			return NextResponse.redirect(`${origin}${next}`);
		}
		const params = new URLSearchParams({
			error: "verify_failed",
			error_description: error.message,
		});
		return NextResponse.redirect(`${origin}/auth/error?${params.toString()}`);
	}

	if (code) {
		const { error } = await supabase.auth.exchangeCodeForSession(code);
		if (!error) {
			return NextResponse.redirect(`${origin}${next}`);
		}
		const params = new URLSearchParams({
			error: "exchange_failed",
			error_description: error.message,
		});
		return NextResponse.redirect(`${origin}/auth/error?${params.toString()}`);
	}

	return NextResponse.redirect(`${origin}/auth/error?error_code=missing_code`);
}
