#!/usr/bin/env bash
# Conductor setup script: boots a local Supabase stack and writes .env.local.
# Safe to re-run — `supabase start` is a no-op if the stack is already up,
# and the env file is regenerated from `supabase status` each time.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v supabase >/dev/null 2>&1; then
  echo "error: supabase CLI not found in PATH" >&2
  exit 1
fi

echo "==> Starting local Supabase"
supabase start

echo "==> Writing .env.local from supabase status"
{
  echo "# Generated by scripts/conductor-setup.sh — re-run to refresh."
  supabase status -o env \
    --override-name api.url=NEXT_PUBLIC_SUPABASE_URL \
    --override-name auth.publishable_key=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY \
    --override-name auth.secret_key=SUPABASE_SECRET_KEY \
    | grep -E '^(NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY|SUPABASE_SECRET_KEY)='
} > .env.local

echo "==> Done. .env.local:"
sed 's/=.*/=***/' .env.local
